In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("LR_MainStreet_BA_WaterTemp_EXO_SourceID_1_QC_1.csv", header=57)

df.index.name = "ValueID"

col = df.pop("WaterTemp_EXO")
df.insert(0, "DataValue", col)
df.insert(1, "ValueAccuracy", "")
df.insert(5, "SiteID", 3)
df.insert(6, "VariableID", 1)
df.insert(7, "OffsetValue", "")
df.insert(8, "OffsetTypeID", "")
df.insert(10, "QualifierID", "")
df.insert(11, "MethodID", 6)
df.insert(12, "SourceID", 1)
df.insert(13, "SampleID", "")
df.insert(14, "DerivedFromID", "")
df.insert(15, "QualityControlLevelID", 1)
toss = df.pop("QualifierCode")

In [3]:
df2 = pd.read_csv("LR_MainStreet_BA_TurbMed_SourceID_1_QC_1.csv", header=59)

df2.index.name = "ValueID"

col = df2.pop("TurbMed")
df2.insert(0, "DataValue", col)
df2.insert(1, "ValueAccuracy", "")
df2.insert(5, "SiteID", 3)
df2.insert(6, "VariableID", 9)
df2.insert(7, "OffsetValue", "")
df2.insert(8, "OffsetTypeID", "")
df2.insert(10, "QualifierID", "")
df2.insert(11, "MethodID", 15)
df2.insert(12, "SourceID", 1)
df2.insert(13, "SampleID", "")
df2.insert(14, "DerivedFromID", "")
df2.insert(15, "QualityControlLevelID", 1)
toss = df2.pop("QualifierCode")

In [4]:
df3 = pd.read_csv("LR_MainStreet_BA_Stage_SourceID_1_QC_1.csv", header=58)

df3.index.name = "ValueID"

col = df3.pop("Stage")
df3.insert(0, "DataValue", col)
df3.insert(1, "ValueAccuracy", "")
df3.insert(5, "SiteID", 3)
df3.insert(6, "VariableID", 15)
df3.insert(7, "OffsetValue", "")
df3.insert(8, "OffsetTypeID", "")
df3.insert(10, "QualifierID", "")
df3.insert(11, "MethodID", 22)
df3.insert(12, "SourceID", 1)
df3.insert(13, "SampleID", "")
df3.insert(14, "DerivedFromID", "")
df3.insert(15, "QualityControlLevelID", 1)
toss = df3.pop("QualifierCode")

In [5]:
df4 = pd.read_csv("LR_MainStreet_BA_SpCond_SourceID_1_QC_1.csv", header=59)

df4.index.name = "ValueID"

col = df4.pop("SpCond")
df4.insert(0, "DataValue", col)
df4.insert(1, "ValueAccuracy", "")
df4.insert(5, "SiteID", 3)
df4.insert(6, "VariableID", 2)
df4.insert(7, "OffsetValue", "")
df4.insert(8, "OffsetTypeID", "")
df4.insert(10, "QualifierID", "")
df4.insert(11, "MethodID", 7)
df4.insert(12, "SourceID", 1)
df4.insert(13, "SampleID", "")
df4.insert(14, "DerivedFromID", "")
df4.insert(15, "QualityControlLevelID", 1)
toss = df4.pop("QualifierCode")

In [6]:
df5 = pd.read_csv("LR_MainStreet_BA_pH_SourceID_1_QC_1.csv", header=57)

df5.index.name = "ValueID"

col = df5.pop("pH")
df5.insert(0, "DataValue", col)
df5.insert(1, "ValueAccuracy", "")
df5.insert(5, "SiteID", 3)
df5.insert(6, "VariableID", 3)
df5.insert(7, "OffsetValue", "")
df5.insert(8, "OffsetTypeID", "")
df5.insert(10, "QualifierID", "")
df5.insert(11, "MethodID", 8)
df5.insert(12, "SourceID", 1)
df5.insert(13, "SampleID", "")
df5.insert(14, "DerivedFromID", "")
df5.insert(15, "QualityControlLevelID", 1)
toss = df5.pop("QualifierCode")

In [7]:
df6 = pd.read_csv("LR_MainStreet_BA_ODO_SourceID_1_QC_1.csv", header=58)

df6.index.name = "ValueID"

col = df6.pop("ODO")
df6.insert(0, "DataValue", col)
df6.insert(1, "ValueAccuracy", "")
df6.insert(5, "SiteID", 3)
df6.insert(6, "VariableID", 4)
df6.insert(7, "OffsetValue", "")
df6.insert(8, "OffsetTypeID", "")
df6.insert(10, "QualifierID", "")
df6.insert(11, "MethodID", 9)
df6.insert(12, "SourceID", 1)
df6.insert(13, "SampleID", "")
df6.insert(14, "DerivedFromID", "")
df6.insert(15, "QualityControlLevelID", 1)
toss = df6.pop("QualifierCode")

In [8]:
df7 = pd.read_csv("LR_MainStreet_BA_ODO_Local_SourceID_1_QC_1.csv", header=58)

df7.index.name = "ValueID"

col = df7.pop("ODO_Local")
df7.insert(0, "DataValue", col)
df7.insert(1, "ValueAccuracy", "")
df7.insert(5, "SiteID", 3)
df7.insert(6, "VariableID", 6)
df7.insert(7, "OffsetValue", "")
df7.insert(8, "OffsetTypeID", "")
df7.insert(10, "QualifierID", "")
df7.insert(11, "MethodID", 11)
df7.insert(12, "SourceID", 1)
df7.insert(13, "SampleID", "")
df7.insert(14, "DerivedFromID", "")
df7.insert(15, "QualityControlLevelID", 1)
toss = df7.pop("QualifierCode")

In [9]:
finaldf = pd.concat([df,df2,df3,df4,df5,df6,df7], ignore_index=True)

In [10]:
finaldf

,DataValue,ValueAccuracy,LocalDateTime,UTCOffset,DateTimeUTC,SiteID,VariableID,OffsetValue,OffsetTypeID,CensorCode,QualifierID,MethodID,SourceID,SampleID,DerivedFromID,QualityControlLevelID
0,3.310000,,2014-01-01 00:00:00,-7.0,2014-01-01 07:00:00,3,1,,,nc,,6,1,,,1
1,3.320000,,2014-01-01 00:15:00,-7.0,2014-01-01 07:15:00,3,1,,,nc,,6,1,,,1
2,3.330000,,2014-01-01 00:30:00,-7.0,2014-01-01 07:30:00,3,1,,,nc,,6,1,,,1
3,3.340000,,2014-01-01 00:45:00,-7.0,2014-01-01 07:45:00,3,1,,,nc,,6,1,,,1
4,3.360000,,2014-01-01 01:00:00,-7.0,2014-01-01 08:00:00,3,1,,,nc,,6,1,,,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2375590,109.534069,,2023-12-18 12:45:00,-7.0,2023-12-18 19:45:00,3,6,,,nc,,11,1,,,1
2375591,109.130000,,2023-12-18 13:00:00,-7.0,2023-12-18 20:00:00,3,6,,,nc,,11,1,,,1
2375592,109.220000,,2023-12-18 13:15:00,-7.0,2023-12-18 20:15:00,3,6,,,nc,,11,1,,,1
2375593,109.310000,,2023-12-18 13:30:00,-7.0,2023-12-18 20:30:00,3,6,,,nc,,11,1,,,1
2375594,109.400000,,2023-12-18 13:45:00,-7.0,2023-12-18 20:45:00,3,6,,,nc,,11,1,,,1

In [11]:
finaldf.to_csv("datavalues.csv")